spring:
  datasource:
    url: jdbc:postgresql://<host_id>/<db_name>
    username: <username>
    password: <pwd>
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
