spring:
  datasource:
    # Replace <DB_NAME> with 'databaseName'
    # Replace <INSTANCE_CONNECTION_NAME> with your Cloud SQL instance connection name (project:region:instance)
    # Replace <DB_USER> with your IAM service account email
    url: jdbc:postgresql:///recommendations?cloudSqlInstance=hsbc-12010598-fdrasp-dev:asia-east2:query-genie-reco-dev-99&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=
    username: query-genie@hsbc-12010598-fdrasp-dev.iam  # Same IAM service account email as above
    #password: ${DB_PASS}  # Leave empty when using IAM authentication
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true     
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Cloud SQL specific configuration
cloud:
  sql:
    # Format: project-id:region:instance-name
    # Example: my-project:us-central1:my-instance
    instance-connection-name: hsbc-12010598-fdrasp-dev:asia-east2:query-genie-reco-dev-99
    
    # Your database name
    database-name: recommendations
    
    # Path to your service account JSON key file
    # Example: /path/to/service-account-key.json
    credentials:
      location: /opt/query-genie/query-genie-main/config/hsbc-12010598-fdrasp-dev-c305fc831d12.json

# Run the application with:
# java -Dspring.config.location=file:/path/to/config/application.yml \
#      -DINSTANCE_CONNECTION_NAME=your-project:region:instance-name \
#      -DDB_NAME=databaseName \
#      -DDB_USER=your-service-account@project.iam.gserviceaccount.com \
#      -DGOOGLE_APPLICATION_CREDENTIALS=/path/to/service-account-key.json \
#      -jar query-genie-1.0.0.jar